# Generated by Django 4.2 on 2023-05-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование ткани')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('type', models.CharField(max_length=200, verbose_name='Состав ткани')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет ткани')),
                ('quantity', models.IntegerField(verbose_name='Количество в наличии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('size', models.CharField(max_length=200, verbose_name='Размеры')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('picture', models.ImageField(upload_to='picture/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabric_shop_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ткани',
                'verbose_name_plural': 'Ткани',
                'ordering': ('name', 'price'),
            },
        ),
    ]
