# Generated by Django 4.2 on 2023-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование ткани')),
                ('type', models.CharField(max_length=200, verbose_name='Состав ткани')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет ткани')),
                ('quantity', models.IntegerField(verbose_name='Количество в наличии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('size', models.CharField(max_length=200, verbose_name='Размеры')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Ткани',
                'verbose_name_plural': 'Ткани',
            },
        ),
    ]
