# Generated by Django 4.2 on 2023-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'ordering': ('name', 'price'), 'verbose_name': 'Ткани', 'verbose_name_plural': 'Ткани'},
        ),
        migrations.AddField(
            model_name='cloth',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
