# Generated by Django 4.2 on 2023-08-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fabric_shop_app.comment', verbose_name='Комментарий к заказу'),
            preserve_default=False,
        ),
    ]
