# Generated by Django 4.2 on 2023-04-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_shop_app', '0003_category_cloth_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
