# Generated by Django 4.2 on 2023-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_shop_app', '0005_alter_category_options_rename_name_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='picture',
            field=models.ImageField(upload_to='picture/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
