# Generated by Django 4.2 on 2023-08-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesettings',
            options={'verbose_name': 'Настройкa', 'verbose_name_plural': 'Настройки'},
        ),
    ]
